# Generated by Django 6.1 on 2026-09-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('outbounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Понятное имя правила для админки', max_length=100)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Меньше — выше приоритет (проверяется раньше)')),
                ('match_type', models.CharField(choices=[('domain', 'Домен'), ('ip', 'IP/CIDR'), ('geosite', 'Geosite'), ('geoip', 'GeoIP'), ('protocol', 'Протокол (http/tls/quic/bittorrent)'), ('port', 'Порт'), ('source_port', 'Исходный порт'), ('network', 'Сеть (tcp/udp)'), ('inbound_tag', "Тег inbound'а-источника")], max_length=20)),
                ('match_values', models.JSONField(default=list, help_text='Список значений для условия, напр. ["geosite:netflix", "geosite:google"]')),
                ('target_balancer_tag', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='core.node')),
                ('target_outbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='outbounds.outbound')),
            ],
            options={
                'ordering': ['node', 'priority'],
                'unique_together': {('node', 'name')},
            },
        ),
    ]
