# Generated by Django 6.1 on 2026-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Только одна тема может быть активна одновременно')),
                ('color_bg', models.CharField(default='#0f1420', help_text='Фон страницы (--bg)', max_length=32)),
                ('color_surface', models.CharField(default='#171d2c', help_text='Фон карточек (--surface)', max_length=32)),
                ('color_border', models.CharField(default='#262e42', help_text='Границы (--border)', max_length=32)),
                ('color_text', models.CharField(default='#e6e9f0', help_text='Основной текст (--text)', max_length=32)),
                ('color_text_muted', models.CharField(default='#8891a7', help_text='Приглушённый текст (--text-muted)', max_length=32)),
                ('color_accent', models.CharField(default='#4f7cff', help_text='Акцентный цвет, кнопки (--accent)', max_length=32)),
                ('color_online', models.CharField(default='#33c481', help_text='Статус «онлайн» (--online)', max_length=32)),
                ('color_offline', models.CharField(default='#6b7385', help_text='Статус «оффлайн» (--offline)', max_length=32)),
                ('color_error', models.CharField(default='#e5484d', help_text='Статус «ошибка» (--error)', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
