# Generated by Django 6.1 on 2026-09-15 09:48

import apps.panel_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_settings', '0002_default_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='FluxCore', max_length=100, verbose_name='Название панели')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.panel_settings.models.branding_upload_path, verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=apps.panel_settings.models.branding_upload_path, verbose_name='Фавиконка')),
                ('custom_css', models.TextField(blank=True, verbose_name='Кастомный CSS')),
                ('ad_enabled', models.BooleanField(default=False, verbose_name='Включить рекламный блок')),
                ('ad_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок объявления')),
                ('ad_content', models.TextField(blank=True, verbose_name='Текст / HTML объявления')),
                ('ad_link', models.URLField(blank=True, verbose_name='Ссылка объявления')),
            ],
            options={
                'verbose_name': 'Брендинг и реклама',
                'verbose_name_plural': 'Брендинг и реклама',
            },
        ),
    ]
