# Generated by Django 5.0.14 on 2026-08-21 06:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('xray', 'Xray-core'), ('sing-box', 'sing-box')], default='xray', max_length=16)),
                ('tag', models.CharField(help_text="Уникальный tag inbound'а в конфиге движка", max_length=100)),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMess'), ('trojan', 'Trojan'), ('shadowsocks', 'Shadowsocks'), ('wireguard', 'WireGuard'), ('mtproto', 'MTProto'), ('hysteria2', 'Hysteria2'), ('hysteria', 'Hysteria'), ('tuic', 'TUIC'), ('anytls', 'AnyTLS'), ('shadowtls', 'ShadowTLS'), ('naiveproxy', 'NaiveProxy'), ('mixed', 'Mixed'), ('http', 'HTTP'), ('tun', 'Tun'), ('tunnel', 'Tunnel')], max_length=20)),
                ('listen', models.CharField(default='0.0.0.0', max_length=64)),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('transport', models.CharField(choices=[('raw', 'Raw (TCP)'), ('xhttp', 'XHTTP'), ('httpupgrade', 'HTTPUpgrade'), ('grpc', 'gRPC'), ('ws', 'WebSocket'), ('mkcp', 'mKCP')], default='raw', max_length=16)),
                ('transport_settings', models.JSONField(blank=True, default=dict, help_text='path, host, service_name и т.п.')),
                ('security', models.CharField(choices=[('none', 'Нет'), ('tls', 'TLS'), ('reality', 'Reality')], default='none', max_length=16)),
                ('security_settings', models.JSONField(blank=True, default=dict, help_text='Для TLS: сертификаты/ключи. Для Reality: dest, private_key, short_ids, server_names')),
                ('sniffing_enabled', models.BooleanField(default=True)),
                ('sniffing_dest_override', models.JSONField(blank=True, default=list, help_text='["http", "tls", "quic"]')),
                ('tcp_mask_enabled', models.BooleanField(default=False)),
                ('tcp_mask_settings', models.JSONField(blank=True, default=dict)),
                ('sockopt', models.JSONField(blank=True, default=dict, help_text='tcpFastOpen, mark, tproxy и т.п.')),
                ('proxy_protocol_enabled', models.BooleanField(default=False)),
                ('http_obfuscation_settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='core.node')),
            ],
            options={
                'ordering': ['node', 'port'],
                'unique_together': {('node', 'port')},
            },
        ),
    ]
