# Generated by Django 6.1 on 2026-09-06 12:20

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='security_settings',
            field=apps.core.fields.EncryptedJSONField(blank=True, default=dict, help_text='Для TLS: сертификаты/ключи. Для Reality: dest, private_key, short_ids, server_names'),
        ),
    ]
