# Generated by Django 5.0.14 on 2026-08-21 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_cascade', models.BooleanField(default=False, help_text='Если True — ноды в этой группе связаны цепочкой (chain outbound → inbound следующей ноды)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(help_text='IP или домен ноды', max_length=255)),
                ('port_agent', models.PositiveIntegerField(default=62050, help_text='Порт агента на ноде')),
                ('port_api', models.PositiveIntegerField(default=62051, help_text='Порт gRPC/API движка')),
                ('engines_enabled', models.JSONField(default=list, help_text='Список активных движков, напр. ["xray", "sing-box"]')),
                ('agent_token', models.CharField(default=uuid.uuid4, help_text='Токен для аутентификации агента ноды перед панелью', max_length=128, unique=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, для гео на карте', max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает установки'), ('online', 'Онлайн'), ('offline', 'Оффлайн'), ('error', 'Ошибка')], default='pending', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Выключить ноду из работы, не удаляя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='core.nodegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NodeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField()),
                ('ram_percent', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('traffic_up_bytes', models.BigIntegerField(default=0)),
                ('traffic_down_bytes', models.BigIntegerField(default=0)),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.node')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['node', 'recorded_at'], name='core_nodeme_node_id_4832e2_idx')],
            },
        ),
    ]
