# Generated by Django 5.0.14 on 2026-08-21 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('default_format', models.CharField(choices=[('happ', 'Happ'), ('v2rayng', 'v2rayNG'), ('clash', 'Clash'), ('sing-box', 'sing-box'), ('raw', 'Сырые ссылки (vless://, vmess:// и т.п.)')], default='happ', max_length=16)),
                ('auto_select_best_server', models.BooleanField(default=False, help_text='Сортировка по пингу на клиенте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clients.client')),
            ],
        ),
    ]
