# Generated by Django 6.1 on 2026-09-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(help_text='Полный лицензионный ключ (payload + подпись)')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('max_nodes', models.PositiveIntegerField(blank=True, help_text='null = без ограничения', null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='null = бессрочная', null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Результат последней проверки подписи/срока')),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
    ]
