# Generated by Django 6.1 on 2026-09-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('max_nodes', models.PositiveIntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('expires_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.RemoveField(
            model_name='license',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='license',
            name='issued_at',
        ),
        migrations.AlterField(
            model_name='license',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.TextField(help_text='Лицензионный ключ, введённый администратором'),
        ),
        migrations.AlterField(
            model_name='license',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='max_nodes',
            field=models.IntegerField(default=1),
        ),
    ]
