# Generated by Django 5.0.14 on 2026-08-21 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbounds', models.ManyToManyField(blank=True, related_name='client_groups', to='inbounds.inbound')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Для vless/vmess', unique=True)),
                ('password', models.CharField(blank=True, help_text='Для trojan/shadowsocks', max_length=128)),
                ('traffic_limit_bytes', models.BigIntegerField(blank=True, help_text='null = безлимит', null=True)),
                ('traffic_used_bytes', models.BigIntegerField(default=0)),
                ('traffic_reset_day', models.PositiveSmallIntegerField(blank=True, help_text='День месяца для авто-сброса трафика (1-28)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='null = бессрочно', null=True)),
                ('max_devices', models.PositiveSmallIntegerField(blank=True, help_text='null = без ограничений', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Владелец клиента в системе (для реселлерки/ЛК)', on_delete=django.db.models.deletion.CASCADE, related_name='vpn_clients', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.clientgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
