# Generated by Django 6.1 on 2026-09-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wg_allowed_ips',
            field=models.CharField(blank=True, help_text='Выделенный IP клиента в тоннеле, напр. 10.0.0.2/32', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='wg_private_key',
            field=models.CharField(blank=True, help_text='Приватный ключ клиента (хранится для генерации конфига/QR, сам сервер его не использует)', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='wg_public_key',
            field=models.CharField(blank=True, help_text='Публичный ключ WireGuard-пира', max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, help_text='Для trojan/shadowsocks/mtproto', max_length=128),
        ),
    ]
