# Generated by Django 6.1 on 2026-09-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('xray', 'Xray-core'), ('sing-box', 'sing-box')], default='xray', max_length=16)),
                ('tag', models.CharField(help_text="Уникальный tag outbound'а в конфиге движка", max_length=100)),
                ('protocol', models.CharField(choices=[('freedom', 'Freedom (прямой выход)'), ('blackhole', 'Blackhole (блокировка)'), ('vless', 'VLESS'), ('vmess', 'VMess'), ('trojan', 'Trojan'), ('shadowsocks', 'Shadowsocks'), ('wireguard', 'WireGuard'), ('http', 'HTTP'), ('socks', 'SOCKS')], default='freedom', max_length=20)),
                ('target_inbound_tag', models.CharField(blank=True, help_text="Tag inbound'а на целевой ноде, к которому подключаемся", max_length=100)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='servers, address, port, credentials и т.п.')),
                ('stream_settings', models.JSONField(blank=True, default=dict, help_text='TLS/Reality/transport для исходящего')),
                ('sockopt', models.JSONField(blank=True, default=dict)),
                ('balancer_tag', models.CharField(blank=True, help_text='Если задано — outbound входит в группу балансировки/failover с этим тегом', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbounds', to='core.node')),
                ('target_node', models.ForeignKey(blank=True, help_text='Если задано — этот outbound соединяется со следующей нодой в цепочке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_outbounds', to='core.node')),
            ],
            options={
                'ordering': ['node', 'tag'],
                'unique_together': {('node', 'tag')},
            },
        ),
    ]
