# Generated by Django 6.1 on 2026-09-06 12:20

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='settings',
            field=apps.core.fields.EncryptedJSONField(blank=True, default=dict, help_text='servers, address, port, credentials и т.п.'),
        ),
    ]
